### ISSUE TITLE
Bug: Website not working

### ISSUE THREAD

**Issue by Wulfheart** [bobbyiliev/introduction-to-sql#1]
https://sql.bobby.sh/

![image](https://user-images.githubusercontent.com/25671390/118668824-7ef83b80-b7f5-11eb-8a31-ac24ed6cb173.png)

**Comment by bobbyiliev** [comment]
Hi @Wulfheart,

This should be fixed now! Thanks for opening an issue for this.

I'm still working on the interactive Katacoda training though.
