### ISSUE TITLE
Feature: In Create table Chapter want to add How to create table from existing table

### ISSUE THREAD

**Issue by maneprajakta** [bobbyiliev/introduction-to-sql#13]
### Is your feature request related to a problem? Please describe.

Create table Chapter don't include point of `How to create a new table from existing table`

### Describe the solution you'd like

I would like to add the point with an example.
Syntax of it 
`
CREATE TABLE new_table
  AS (SELECT * FROM old_table);
`

### Additional context
Want to contribute as part of Hacktoberfest 2021

**Comment by maneprajakta** [comment]
@bobbyiliev can you assign me this if it is vallid.

**Comment by bobbyiliev** [comment]
I like the suggestion! Looking forward to your PR @maneprajakta
