### ISSUE TITLE
Feature: Want to add point How to Rename a Table in creating-tables chapter

### ISSUE THREAD

**Issue by maneprajakta** [bobbyiliev/introduction-to-sql#15]
### Is your feature request related to a problem? Please describe.

creating-tables Chapter does not describe how to rename  a table

### Describe the solution you'd like
Add rename table point along with example 
### Additional context
Contributing  as part of Hactoberest 2021

**Comment by maneprajakta** [comment]
@bobbyiliev can you assign me this if it is vallid.

**Comment by bobbyiliev** [comment]
Sounds great! Just assigned you to this issue
