### ISSUE TITLE
Bug: Contibuting.md is not up to date

### ISSUE THREAD

**Issue by maneprajakta** [bobbyiliev/introduction-to-sql#16]
`File Location/Types` in Contributing.md doesn't match the current project structure will update that.

### To Reproduce

1.Visit : [This](https://github.com/bobbyiliev/introduction-to-sql/blob/main/CONTRIBUTING.md#file-locationtypes)
There are no translations of the book present in the repo now will change it as per the current structure.

### Expected behavior

Current structure explanation

### Additional context

I Will work on it as part of Hacktoberfest 2021

**Comment by maneprajakta** [comment]
@bobbyiliev can you assign me this if it is vallid.

**Comment by bobbyiliev** [comment]
Sounds good, maybe add valid links as an example and also keep the `{LANG}` in there in case that there are some translations in the future. Let me know what you think

**Comment by maneprajakta** [comment]
@bobbyiliev sounds good will do that!
