### ISSUE TITLE
Feature:  want to add about truncate table in table chapter

### ISSUE THREAD

**Issue by nishajha629** [bobbyiliev/introduction-to-sql#23]
### Is your feature request related to a problem? Please describe.
want to add about truncate table in table chapter

### Describe the solution you'd like
The TRUNCATE TABLE command deletes the data inside a table, but not the table itself.

### Additional context
contributing to hacktoberfest 2021

**Comment by nishajha629** [comment]
could you please assign me this issue if you feel it's valid

**Comment by bobbyiliev** [comment]
Sounds good! Just assigned you to this issue
