### ISSUE TITLE
Feature: More use cases for SELECT Clause

### ISSUE THREAD

**Issue by vishalsharma1997** [bobbyiliev/introduction-to-sql#33]
Hi ,

There is a scope of improvement in the **select.md** file.
More use cases can be added along with examples.

I would like to contribute for the same.
Kindly assign this issue to me.

> **Note** :- _I have added some examples and use cases and raised a PR for the same._

**Comment by bobbyiliev** [comment]
Sounds good! I've just merged your PR:

https://github.com/bobbyiliev/introduction-to-sql/pull/32

Thank you for your contribution!
