### ISSUE TITLE
Feature: More Use cases of INSERT Clause

### ISSUE THREAD

**Issue by vishalsharma1997** [bobbyiliev/introduction-to-sql#38]
Hi ,

There is a scope of improvement in the **insert.md** file.
More use cases can be added along with examples.

I would like to contribute for the same.
Kindly assign this issue to me.

**Comment by bobbyiliev** [comment]
Hi there @vishalsharma1997, sounds great! A PR would be really appreciated!

**Comment by vishalsharma1997** [comment]
Hi @bobbyiliev ,
Thanks for providing me with this opportunity.
I have raised the PR for the same with some use cases.
PR Link :- [Use case of Insert clause to add multiple records using another table](https://github.com/bobbyiliev/introduction-to-sql/pull/39)

Kindly review this.

**Comment by bobbyiliev** [comment]
Thank you for this great contribtuon! Just merged it!
