### ISSUE TITLE
Feature: 

### ISSUE THREAD

**Issue by vibuverma** [bobbyiliev/introduction-to-sql#8]
### Is your feature request related to a problem? Please describe.

Links to chapters are not added.
### Describe the solution you'd like
Adding links to chapters in README.md

### Additional context
please consider this for Hacktoberfest 2021.

**Comment by bottercode** [comment]
I would like to work on this issue. Please assign me.

**Comment by Himanshu-Agg12** [comment]
Please assign this task to me under Hacktoberfest 2021

**Comment by viveknshah** [comment]
Did I get the use case right with #12 ?

**Comment by andrewasche** [comment]
Can I get assigned to this task for HACK toberfest 21
